package model

// These models will be used until they are automatically generated by gqlgen

// ChatMessage represents a single message in a conversation
type ChatMessage struct {
	ID        string `json:"id"`
	Content   string `json:"content"`
	Sender    string `json:"sender"`
	Timestamp string `json:"timestamp"`
}

// ChatResponse represents a response from the chatbot
type ChatResponse struct {
	ID        string `json:"id"`
	Content   string `json:"content"`
	Timestamp string `json:"timestamp"`
}
