// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Announcement struct {
	ID        string  `json:"id"`
	CourseID  string  `json:"courseId"`
	Title     *string `json:"title,omitempty"`
	Content   string  `json:"content"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
}

type Course struct {
	ID            string          `json:"id"`
	Name          string          `json:"name"`
	Semester      string          `json:"semester"`
	Description   *string         `json:"description,omitempty"`
	CreatedAt     string          `json:"createdAt"`
	UpdatedAt     string          `json:"updatedAt"`
	Staff         []*Staff        `json:"staff"`
	Students      []*Student      `json:"students"`
	Announcements []*Announcement `json:"announcements"`
	Homework      []*Homework     `json:"homework"`
}

type Grade struct {
	ID         string  `json:"id"`
	StudentID  string  `json:"studentId"`
	CourseID   string  `json:"courseId"`
	Semester   string  `json:"semester"`
	GradeType  string  `json:"gradeType"`
	ItemID     string  `json:"itemId"`
	GradeValue string  `json:"gradeValue"`
	GradedBy   *string `json:"gradedBy,omitempty"`
	Comments   *string `json:"comments,omitempty"`
	GradedAt   string  `json:"gradedAt"`
	UpdatedAt  string  `json:"updatedAt"`
}

type Homework struct {
	ID          string `json:"id"`
	CourseID    string `json:"courseId"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Workflow    string `json:"workflow"`
	DueDate     string `json:"dueDate"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type Mutation struct {
}

type NewAnnouncement struct {
	CourseID string  `json:"courseId"`
	Title    *string `json:"title,omitempty"`
	Content  string  `json:"content"`
}

type NewCourse struct {
	Name        string  `json:"name"`
	Semester    string  `json:"semester"`
	Description *string `json:"description,omitempty"`
}

type NewGrade struct {
	StudentID  string  `json:"studentId"`
	CourseID   string  `json:"courseId"`
	Semester   string  `json:"semester"`
	GradeType  string  `json:"gradeType"`
	ItemID     string  `json:"itemId"`
	GradeValue string  `json:"gradeValue"`
	GradedBy   *string `json:"gradedBy,omitempty"`
	Comments   *string `json:"comments,omitempty"`
}

type NewHomework struct {
	CourseID    string `json:"courseId"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Workflow    string `json:"workflow"`
	DueDate     string `json:"dueDate"`
}

type NewStaff struct {
	FirstName   string  `json:"firstName"`
	LastName    string  `json:"lastName"`
	Email       string  `json:"email"`
	PhoneNumber string  `json:"phoneNumber"`
	Title       *string `json:"title,omitempty"`
	Office      *string `json:"office,omitempty"`
}

type NewStudent struct {
	FirstName   string `json:"firstName"`
	LastName    string `json:"lastName"`
	Email       string `json:"email"`
	PhoneNumber string `json:"phoneNumber"`
}

type Query struct {
}

type Staff struct {
	ID          string  `json:"id"`
	FirstName   string  `json:"firstName"`
	LastName    string  `json:"lastName"`
	Email       string  `json:"email"`
	PhoneNumber string  `json:"phoneNumber"`
	Title       *string `json:"title,omitempty"`
	Office      *string `json:"office,omitempty"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
}

type Student struct {
	ID          string `json:"id"`
	FirstName   string `json:"firstName"`
	LastName    string `json:"lastName"`
	Email       string `json:"email"`
	PhoneNumber string `json:"phoneNumber"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type Submission struct {
	ID          string `json:"id"`
	HomeworkID  string `json:"homeworkId"`
	StudentID   string `json:"studentId"`
	SubmittedAt string `json:"submittedAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type UpdateCourse struct {
	Name        *string `json:"name,omitempty"`
	Semester    *string `json:"semester,omitempty"`
	Description *string `json:"description,omitempty"`
}

type UpdateGrade struct {
	GradeValue *string `json:"gradeValue,omitempty"`
	Comments   *string `json:"comments,omitempty"`
}

type UpdateStaff struct {
	FirstName   *string `json:"firstName,omitempty"`
	LastName    *string `json:"lastName,omitempty"`
	Email       *string `json:"email,omitempty"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
	Title       *string `json:"title,omitempty"`
	Office      *string `json:"office,omitempty"`
}

type UpdateStudent struct {
	FirstName   *string `json:"firstName,omitempty"`
	LastName    *string `json:"lastName,omitempty"`
	Email       *string `json:"email,omitempty"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
}
